language: ruby

before_install: 
  #- source ~/.rvm/scripts/rvm && rvm use 2.2.0
  - gem update --system

rvm:
 # - 1.8.7
  #- 1.9.3
  #- 2.0.0
  #- 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  
#build_image: shippable/minv2:beta
